"""init health schema

Revision ID: 117efa139a13
Revises: 
Create Date: 2026-07-06 23:03:40.182394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '117efa139a13'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key'),
    schema='health'
    )
    op.create_table('body_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('body_fat_pct', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('muscle_mass_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('skeletal_muscle_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bmr_kcal', sa.Integer(), nullable=True),
    sa.Column('body_water_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('visceral_fat_level', sa.Integer(), nullable=True),
    sa.Column('waist_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('bp_systolic', sa.Integer(), nullable=True),
    sa.Column('bp_diastolic', sa.Integer(), nullable=True),
    sa.Column('resting_hr', sa.Integer(), nullable=True),
    sa.Column('spo2_pct', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('sleep_hours', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('sleep_quality', sa.Integer(), nullable=True),
    sa.Column('morning_erection', sa.Boolean(), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('autofilled', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('energy_level BETWEEN 1 AND 5', name='ck_energy_level'),
    sa.CheckConstraint('sleep_quality BETWEEN 1 AND 5', name='ck_sleep_quality'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('log_date'),
    schema='health'
    )
    op.create_table('daily_activity',
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Integer(), nullable=True),
    sa.Column('active_kcal', sa.Numeric(precision=7, scale=1), nullable=True),
    sa.Column('hr_min', sa.Integer(), nullable=True),
    sa.Column('hr_avg', sa.Integer(), nullable=True),
    sa.Column('hr_max', sa.Integer(), nullable=True),
    sa.Column('source', sa.Text(), server_default='samsung_zip', nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('log_date'),
    schema='health'
    )
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('progression_group', sa.Text(), nullable=True),
    sa.Column('level', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('equipment', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='health'
    )
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('kcal_per_100g', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('fat_g', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('carb_g', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('tcm_tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='health'
    )
    op.create_table('habits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('period', sa.Text(), server_default='daily', nullable=False),
    sa.Column('target_per_period', sa.Integer(), server_default='1', nullable=False),
    sa.Column('time_hint', sa.Text(), nullable=True),
    sa.Column('auto_rule', sa.Text(), nullable=True),
    sa.Column('source_doc', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sort', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("period IN ('daily','weekly')", name='ck_habit_period'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='health'
    )
    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('inserted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('skipped', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failed', sa.Integer(), server_default='0', nullable=False),
    sa.Column('report', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','running','done','failed')", name='ck_import_job_status'),
    sa.PrimaryKeyConstraint('id'),
    schema='health'
    )
    op.create_table('import_raw',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('record_type', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blob', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_offset', sa.Text(), nullable=True),
    sa.Column('parse_status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('parse_error', sa.Text(), nullable=True),
    sa.Column('parse_version', sa.Integer(), server_default='0', nullable=False),
    sa.Column('imported_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("parse_status IN ('pending','parsed','failed','skipped')", name='ck_parse_status'),
    sa.CheckConstraint("source IN ('samsung_zip','health_connect','keep_api','keep_file')", name='ck_import_source'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'record_type', 'external_id', name='ux_import_raw_ext'),
    schema='health'
    )
    op.create_index('ix_import_raw_replay', 'import_raw', ['source', 'record_type'], unique=False, schema='health', postgresql_where=sa.text("parse_status IN ('pending','failed')"))
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('ingredients', sa.Text(), nullable=False),
    sa.Column('method', sa.Text(), nullable=True),
    sa.Column('effects', sa.Text(), nullable=True),
    sa.Column('effect_tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('contraindications', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='health'
    )
    op.create_table('sleep_sessions',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('start_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('wake_date', sa.Date(), nullable=False),
    sa.Column('awake_min', sa.Integer(), nullable=True),
    sa.Column('light_min', sa.Integer(), nullable=True),
    sa.Column('deep_min', sa.Integer(), nullable=True),
    sa.Column('rem_min', sa.Integer(), nullable=True),
    sa.Column('total_sleep_min', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='ux_sleep_sessions_ext'),
    schema='health'
    )
    op.create_index('ix_sleep_sessions_wake_date', 'sleep_sessions', ['wake_date'], unique=False, schema='health')
    op.create_table('sync_state',
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('last_success_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False),
    sa.Column('needs_reauth', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('watermark', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('source'),
    schema='health'
    )
    op.create_table('weekly_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metrics_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('extract(isodow FROM week_start) = 1', name='ck_week_monday'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('week_start'),
    schema='health'
    )
    op.create_table('workout_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.Column('source_doc', sa.Text(), nullable=True),
    sa.Column('content_md', sa.Text(), nullable=True),
    sa.Column('weekly_template', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('phases', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='health'
    )
    op.create_table('diet_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('meal', sa.Text(), nullable=False),
    sa.Column('food_id', sa.Integer(), nullable=True),
    sa.Column('free_text', sa.Text(), nullable=True),
    sa.Column('amount_g', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('kcal', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('protein_g', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("meal IN ('早餐','午餐','晚餐','加餐')", name='ck_meal'),
    sa.CheckConstraint('food_id IS NOT NULL OR free_text IS NOT NULL', name='ck_diet_target'),
    sa.ForeignKeyConstraint(['food_id'], ['health.foods.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='health'
    )
    op.create_index('idx_diet_logs_date', 'diet_logs', ['log_date'], unique=False, schema='health')
    op.create_table('habit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habit_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('done_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('done_count > 0', name='ck_done_count'),
    sa.ForeignKeyConstraint(['habit_id'], ['health.habits.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('habit_id', 'log_date', name='ux_habit_logs'),
    schema='health'
    )
    op.create_index('idx_habit_logs_date', 'habit_logs', ['log_date'], unique=False, schema='health')
    op.create_table('plan_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Text(), server_default='active', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active','done','abandoned')", name='ck_enroll_status'),
    sa.ForeignKeyConstraint(['plan_id'], ['health.workout_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='health'
    )
    op.create_table('workout_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=True), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('enrollment_id', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.Text(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('calories', sa.Integer(), nullable=True),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('rpe', sa.Integer(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.Text(), server_default='manual', nullable=False),
    sa.Column('external_id', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source = 'manual' OR external_id IS NOT NULL", name='ck_ext_required'),
    sa.CheckConstraint("source IN ('manual','keep','samsung_zip','health_connect')", name='ck_workout_source'),
    sa.CheckConstraint('rpe BETWEEN 1 AND 10', name='ck_rpe'),
    sa.ForeignKeyConstraint(['enrollment_id'], ['health.plan_enrollments.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['health.workout_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='health'
    )
    op.create_index('idx_workout_logs_date', 'workout_logs', ['log_date'], unique=False, schema='health')
    op.create_index('ux_workout_logs_ext', 'workout_logs', ['source', 'external_id'], unique=True, schema='health', postgresql_where=sa.text('external_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_workout_logs_ext', table_name='workout_logs', schema='health', postgresql_where=sa.text('external_id IS NOT NULL'))
    op.drop_index('idx_workout_logs_date', table_name='workout_logs', schema='health')
    op.drop_table('workout_logs', schema='health')
    op.drop_table('plan_enrollments', schema='health')
    op.drop_index('idx_habit_logs_date', table_name='habit_logs', schema='health')
    op.drop_table('habit_logs', schema='health')
    op.drop_index('idx_diet_logs_date', table_name='diet_logs', schema='health')
    op.drop_table('diet_logs', schema='health')
    op.drop_table('workout_plans', schema='health')
    op.drop_table('weekly_reviews', schema='health')
    op.drop_table('sync_state', schema='health')
    op.drop_index('ix_sleep_sessions_wake_date', table_name='sleep_sessions', schema='health')
    op.drop_table('sleep_sessions', schema='health')
    op.drop_table('recipes', schema='health')
    op.drop_index('ix_import_raw_replay', table_name='import_raw', schema='health', postgresql_where=sa.text("parse_status IN ('pending','failed')"))
    op.drop_table('import_raw', schema='health')
    op.drop_table('import_jobs', schema='health')
    op.drop_table('habits', schema='health')
    op.drop_table('foods', schema='health')
    op.drop_table('exercises', schema='health')
    op.drop_table('daily_activity', schema='health')
    op.drop_table('body_metrics', schema='health')
    op.drop_table('app_settings', schema='health')
    # ### end Alembic commands ###
